config/routes.rb
Blog::Application.routes.draw do
  get "sitemap/index"

  devise_for :users

  resources :articles do
    resources :comments
  end

  
  root :to => "articles#index"

  match "/sitemap" => "sitemap#index", :as => :sitemap, :defaults => {:format => :xml}
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
 
    if user.role? :Admin
      can :manage, :all
      can :publish, Article
    elsif user.role? :Moderator
      can :read, [Article, Comment]
      can [:edit, :update], Comment
    elsif user.role? :Member
       can :read, :all
       can :create, [Article, Comment]
       can [:edit, :update], Comment
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  validates_presence_of :title, :body
  validates_uniqueness_of :title
  attr_writer :tag_names
  after_save :assign_tags
  
  def tag_names
    @tag_names || tags.map(&:name).join(' ')
  end
  
  private
  
  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/\,/).map do |name|
        Tag.find_or_create_by_name(name)
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates_presence_of :name, :email, :body
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy  
  has_many :articles, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :article  
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_and_belongs_to_many :roles
  
  def role?(role)
     return !!self.roles.find_by_name(role.to_s)
   end
   
   before_create :setup_role
   private
   def setup_role
     if self.roles.empty?
       self.roles << Role.find_by_name("Administrator")
     end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  respond_to :html, :json
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    respond_with(@articles = Article.all)
  end

  def show
    respond_with(@article = Article.find(params[:id]))
  end

  def new
    respond_with(@article = Article.new)
  end

  def edit
    authorize! :edit, @article
    respond_with(@article = Article.find(params[:id]))
  end

  def create
    authorize! :create, @article
    @article = Article.create(params[:article].merge({ :user => current_user }))
    respond_with(@article, :location => articles_url)
  end

  def update
    authorize! :update, @article
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])
    respond_with(@article, :location => articles_url)
  end

  def destroy
    authorize! :destroy, @article
    @article = Article.find(params[:id])
    @article.destroy
    respond_with(@article)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.xml
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @article = Article.find(params[:article_id])
      @comment = @article.comments.build(params[:comment])
      respond_to do |format|
        if @comment.save
          format.html { redirect_to(@article, :notice => 'Comment was successfully created.') }
          format.xml  { render :xml => @article, :status => :created, :location => @article }
        else
          format.html { redirect_to(@article, :notice => 
          'Comment could not be saved. Please fill in all fields')}
          format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
        end
      end
    end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
      @comment = Comment.find(params[:id])
      @article = @comment.article
      respond_to do |format|
        if @comment.update_attributes(params[:comment])
          format.html { redirect_to(@article, :notice => 'Comment was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
        end
      end
    end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
      @comment = Comment.find(params[:id])
      @article = Article.find(params[:article_id])
      @comment.destroy

      respond_to do |format|
        format.html { redirect_to(@article, :notice => 'Comment was successfully deleted.') }
        format.xml  { head :ok }
      end
    end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  layout nil

  def index
    @articles = Article.all
    headers["Content-Type"] = "text/xml"
    respond_to do |format|
      format.xml { render :layout => false }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def print_time(timestamp)
    timestamp.strftime("%m/%d/%Y %I:%M:%S %p")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/views/articles/_article.html.erb
<p>
  <%= article.title %>
</p>

<p>
  <%= article.body %>
</p>
<%= link_to 'Show', article %>
<% if can? :update, article  %>
  <%= link_to 'Edit', edit_article_path(article) %>
<% end %>
<% if can? :delete, article  %>
  <%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<div class="field">
    <%= f.label :tag_names, "Tags" %>  
    <%= f.text_field :tag_names %>  
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render @articles %>
<br />
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div id="article-content" class="span-17">
  <div class="article_title">
  <h1><%= @article.title %></h1>
  </div>
 <div class="article_body">
    <p>
    By
    <%= @article.user ? @article.user.email : "Unkown" %>
    on <%= print_time(@article.created_at) %>
    </p>
    <p>
      <%= @article.body %>
  <p>Tags:
    <% @article.tags.each do |tag|%>
      <%= tag.name %>
     <% end %>
  </p>
    </p>
  </div>
</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<h2>Comments</h2>
<div id ="comments">
  <%= render :partial => @article.comments %>
</div>

<%= form_for([@article, @article.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/_comment.html.erb
<% div_for comment do %>
  <div id = "comment_author" class="yellow">
  <%= comment.name %>
  <%= link_to 'Edit', edit_article_comment_path(@article, comment) %>
  <%= link_to 'Delete', article_comment_path(@article, comment), :confirm => 'Are you sure?', :method => :delete %>
  </div>
  <div id = "comment_created_at">
  <%= print_time(comment.created_at) %>
  </div>
  <div id = "comment_text">
<div><%= comment.body %></div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.text_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for([:article, @comment]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Article</th>
    <th>Name</th>
    <th>Email</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.article_id %></td>
    <td><%= comment.name %></td>
    <td><%= comment.email %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<% div_for comment do %>
  <p>
  <p>
    <b>Name:</b>
    <%= comment.name %>
  </p>

  <p>
    <b>Email:</b>
    <%= comment.email %>
  </p>

  <p>
    <b>Body:</b>
    <%= comment.body %>
  </p>

<%= link_to 'Edit', edit_article_comment_path(@article, comment) %> |
<%= link_to 'Delete', article_comment_path(@article, comment), :confirm => 'Are you sure?', :method => :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Josh In Exile</title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= stylesheet_link_tag 'screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'print',  :media => 'print' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>

<body>
<div class= "container">
  <div class="span-17 colborder" id="content">
    <%= image_tag "banner.png", { :height => '175px', :width => '690px' } %>
    <%= yield %>
  </div>
  <div class="span-4 last" id="sidebar"></div>
</div>
</body>
</html>

app/views/sitemap/index.html.erb
<h1>Sitemap#index</h1>
<p>Find me in app/views/sitemap/index.html.erb</p>